local whichkey = require("which-key")

whichkey.setup({
	preset = "helix",
	delay = 0,
	defaults = {},
	show_help = true,
	spec = {
		-- individual keymaps với describe
		{ "<leader>ta", icon = { icon = "󰱑", hl = "MiniIconsGreen" }, desc = "Toggle all" },
		{ "<leader>tf", icon = { icon = "󰱑", hl = "MiniIconsGreen" }, desc = "Toggle file" },
		{ "<leader>K", icon = { icon = "󰋽", hl = "MiniIconsBlue" }, desc = "Show information" },
		{ "<leader>v", icon = { icon = "", hl = "MiniIconsYellow" }, desc = "View something" },
		{ "<leader>cm", icon = { icon = "󱁤", hl = "MiniIconsGrey" }, desc = "Code map" },
		-- groups với describe
		{ "<leader>b", group = "Buffer", desc = "Buffer commands" },
		{ "<leader>c", group = "Code", desc = "Code commands" },
		{ "<leader>f", group = "File/Find", desc = "File and Find" },
		{ "<leader>g", group = "Git", desc = "Git commands" },
		{ "<leader>gh", group = "Hunks", desc = "Git hunks" },
		{ "<leader>n", group = "Noice", desc = "Noice commands" },
		{ "<leader>r", group = "Run", icon = { icon = "", hl = "MiniIconsRed" }, desc = "Run code" },
		{ "<leader>s", group = "Search", desc = "Search tools" },
		{ "<leader>S", group = "Session", desc = "Session management" },
		{ "<leader>t", group = "Test", icon = { icon = "󰱑", hl = "MiniIconsGreen" }, desc = "Testing" },
		{ "<leader>T", group = "Terminal", desc = "Terminal commands" },
		{ "<leader>u", group = "UI", desc = "UI tweaks" },
		{ "<leader>w", group = "Window", desc = "Window management" },
		{ "<leader>x", group = "Diagnostics/Quickfix", desc = "Diagnostics" },
		{ "<leader><Tab>", group = "Tab", desc = "Tab commands" },
	},
	win = {
		border = "double",
		no_overlap = false,
	},
	disable = {
		ft = { "markdown" },
	},
	icons = {
		mappings = true,
		key = {
			Up = "↑ Up",
			Down = "↓ Down",
			Left = "← Left",
			Right = "→ Right",
			C = "⌃ Control",
			M = " Windows",
			D = "⌦ Del",
			S = "⇧ Shift",
			CR = "⏎ Enter",
			Esc = "<esc>",
			ScrollWheelDown = "⇩",
			ScrollWheelUp = "⇧",
			NL = "⏎",
			BS = "⌫ bs",
			Space = "␣",
			Tab = "⇥",
			F1 = "F1",
			F2 = "F2",
			F3 = "F3",
			F4 = "F4",
			F5 = "F5",
			F6 = "F6",
			F7 = "F7",
			F8 = "F8",
			F9 = "F9",
			F10 = "F10",
			F11 = "F11",
			F12 = "F12",
		},
	},
})
